### ISSUE TITLE
DataCredito login change, now send a code by email

### ISSUE THREAD

**Issue by AndresMorelos** [FlavioAandres/Lambdas-WP#43] opened 2021-03-03 00:01 UTC
DataCredito app now sends a code by email to ensure the user login; we need to look for a bypass via API request or scrapper.

The bypass via API request will be the priority.

**Comment by FlavioAandres** [comment] 2021-05-17 01:23
The problem is only through the login? I mean, if we can break the login the backend allow us receive all the PRO information?

**Comment by AndresMorelos** [comment] 2021-05-17 20:10
@FlavioAandres Some days after this issue was opened, they change thier backend to verify if there is any payment from the user. :(

**Comment by FlavioAandres** [comment] 2021-06-08 12:51
I think we can close this until we know a better way to implement data credito again 😅

**Closed** 2021-06-08 12:51 UTC
